dist: xenial   # required for Python >= 3.7

language: python

python:
  - "3.7"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements.txt

matrix:
  include:	
    - name: Test 
      script: ./scripts/test.sh && codecov && codecov --token=$CODECOV_TOKEN
    - name: Lint
      script: ./scripts/lint.sh
