site_name: Dataclasses Avro Schema
site_description: avro, kafka, client, avro schema, apache, python

theme:
    name: 'material'

repo_name: marcosschroh/dataclasses-avroschema
repo_url: https://github.com/marcosschroh/dataclasses-avroschema

nav:
    - Introduction: 'index.md'
    - Avro Schema and Python Classes: 'avro_schema.md'
    - Fields Specification: 'fields_specification.md'
    - Primitive Types: 'primitive_types.md'
    - Complex Types: 'complex_types.md'
    - Logical Types: 'logical_types.md'
    - Schema Relationships: 'schema_relationships.md'

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - admonition
  - codehilite
  - extra
